sudo: false
language: node_js
node_js: 8

cache:
  directories:
    - ~/.npm
    - ~/.cache

notifications:
  email: false

jobs:
  include:
    - stage: test
      script:
        - npm run test:cypress
        - npm run test:jest:dist
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release