sudo: false
language: node_js
node_js: 8

cache:
  directories:
    - ~/.npm
    - ~/.cache

notifications:
  email: false

addons:
  apt:
    packages:
      - libgconf-2-4

jobs:
  include:
    - stage: test
      script:
        - npm run test:cypress
        - npm run test:jest:dist
    - stage: release
      node_js: lts/*
      script:
        - npm run test:jest:src:coverage:coveralls
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release
